#!/usr/bin/env ruby

# frozen_string_literal: true

require 'httparty'

class Servers
  include HTTParty

  PLAYA_CONFIG_URL = 'https://sfgame.net/config.json'

  def initialize(argv:)
  end

  def run
    config = JSON.parse(self.class.get(PLAYA_CONFIG_URL).body)

    servers = config['servers'].each_with_object({}) do |server, memo|
      memo[server['i'].to_s] = server['d']
    end

    File.write('servers.json', JSON.pretty_generate(servers))
  end
end

Servers.new(argv: ARGV).run if __FILE__ == $0
