#!/usr/bin/env ruby

# frozen_string_literal: true

require 'httparty'
require 'fileutils'
require 'json'

module Synchronize
  module_function

  PLAYA_CONFIG_URL = 'https://sfgame.net/config.json'
  PLAYA_TRANSLATION_URL = '%<prefix>s%<version>s/sfgame_%<language>s.bin'

  REGEXP_MONSTER = /^monster_name_(\d+)$/ 
  REGEXP_ITEM = /^item_type_(\d+)_(?:class_(\d+)_)?pic_(\d+)$/
  REGEXP_PET_REQUIREMENT = /^pet_requirements_(fire|water|earth|shadow|light)_(\d\d)$/
  REGEXP_RAID_NAME = /^guild_raid_name_(\d+)$/
  REGEXP_ACHIEVEMENT = /^album_ach_(\d+)_title$/

  LANGUAGE_LIST = {
    'en' => 'en',
    'de' => 'de',
    'pl' => 'pl',
    # 'pt' => 'pt',
    'cs' => 'cs',
    'fr' => 'fr',
    'it' => 'it',
    'es' => 'es',
    'hu' => 'hu',
    'ch' => 'de'
  }

  def call(argv:)
    config = JSON.parse(HTTParty.get(PLAYA_CONFIG_URL).body)

    # Save translations
    LANGUAGE_LIST.each do |sftools_language, playa_language|
      FileUtils.mkdir_p("lang/#{sftools_language}")

      response = HTTParty.get(format(PLAYA_TRANSLATION_URL, prefix: config['language_path'], version: config['required_client_version_min'][..3] + '00', language: playa_language))
      unless response.success?
        puts "[#{sftools_language}] Failed to fetch #{playa_language}"
        puts response.body

        next
      end

      strings = decode(response.body)

      monsters = strings.select { |key, _| key.match?(REGEXP_MONSTER) }
      monsters = monsters.map do |key, text|
        [
          key[REGEXP_MONSTER, 1].to_i,
          text.split('|').first
        ]
      end.to_h

      File.write("lang/#{sftools_language}/monsters.json", JSON.pretty_generate(monsters))

      items = strings.select { |key, _| key.match?(REGEXP_ITEM) }
      items = items.map do |key, text|
        [
          key,
          text.split('|').first
        ]
      end.to_h

      File.write("lang/#{sftools_language}/items.json", JSON.pretty_generate(items))

      general = strings.select { |key, _| [REGEXP_PET_REQUIREMENT, REGEXP_RAID_NAME, REGEXP_ACHIEVEMENT].any? { key.match?(_1) } }
      general = general.map do |key, text|
        parsed_key = case key
        when REGEXP_PET_REQUIREMENT
          "pet_requirement_#{%w[shadow light earth fire water].index(Regexp.last_match(1)) * 20 + Regexp.last_match(2).to_i - 1}"
        when REGEXP_RAID_NAME
          "guild_raid_#{Regexp.last_match(1).to_i}"
        when REGEXP_ACHIEVEMENT
          "achievement_#{Regexp.last_match(1).to_i - 1}"
        else
          key
        end

        [
          parsed_key,
          text.split('|').first.gsub(/<br>/, ' ')
        ]
      end.to_h

      File.write("lang/#{sftools_language}/general.json", JSON.pretty_generate(general))
    end
  end

  def decode(text)
    bytes = text.bytes

    read_value = lambda do |bytes|
      head_len = bytes.shift.ord
      head_len += 64 * (2 * bytes.shift - 2) if bytes.first.ord <= 32
 
      bytes.shift(head_len).map(&:chr).join
    end
    
    strings = {}
    until bytes.empty?
      key = read_value.call(bytes)
      val = read_value.call(bytes)

      strings[key.force_encoding(Encoding::UTF_8)] = val.force_encoding(Encoding::UTF_8)
    end
    
    hash = Hash[strings.sort_by { |key, val| key.to_s }]
  end
  private_class_method :decode
end

Synchronize.call(argv: ARGV) if __FILE__ == $0
